-- MySQL Script generated by MySQL Workbench
-- ven. 17 juin 2022 23:09:28
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SkillZBox
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SkillZBox` ;

-- -----------------------------------------------------
-- Schema SkillZBox
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SkillZBox` ;
USE `SkillZBox` ;

-- -----------------------------------------------------
-- Table `SkillZBox`.`USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkillZBox`.`USER` ;

CREATE TABLE IF NOT EXISTS `SkillZBox`.`USER` (
  `email` VARCHAR(255) NOT NULL,
  `username` VARCHAR(16),
  `activityMessage` VARCHAR(120) NULL,
  `password` BINARY(255) NOT NULL,
  `isVerified` TINYINT NOT NULL DEFAULT 0,
  `role` ENUM("admin", "moderator", "user") NOT NULL DEFAULT 'user',
  `isConnected` TINYINT NOT NULL DEFAULT 0,
  `isBlackListed` TINYINT NOT NULL DEFAULT 0,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `SkillZBox`.`ROOM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkillZBox`.`ROOM` ;

CREATE TABLE IF NOT EXISTS `SkillZBox`.`ROOM` (
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `optionLimitUser` INT NOT NULL DEFAULT 10,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkillZBox`.`USER_LOGO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkillZBox`.`USER_LOGO` ;

CREATE TABLE IF NOT EXISTS `SkillZBox`.`USER_LOGO` (
  `path` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `seed` INT NOT NULL,
  `sizeMo` INT NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 0,
  `userUuid` BINARY(16) NOT NULL,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_USER_LOGO_1_idx` (`userUuid` ASC) VISIBLE,
  CONSTRAINT `fk_USER_LOGO_1`
    FOREIGN KEY (`userUuid`)
    REFERENCES `SkillZBox`.`USER` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkillZBox`.`USER_IP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkillZBox`.`USER_IP` ;

CREATE TABLE IF NOT EXISTS `SkillZBox`.`USER_IP` (
  `ip` VARCHAR(16) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `active` TINYINT NOT NULL DEFAULT 0,
  `userUuid` BINARY(16) NOT NULL,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_USER_IP_1_idx` (`userUuid` ASC) VISIBLE,
  CONSTRAINT `fk_USER_IP_1`
    FOREIGN KEY (`userUuid`)
    REFERENCES `SkillZBox`.`USER` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkillZBox`.`USER_MACADDRESS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkillZBox`.`USER_MACADDRESS` ;

CREATE TABLE IF NOT EXISTS `SkillZBox`.`USER_MACADDRESS` (
  `macAddress` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `active` TINYINT NOT NULL DEFAULT 0,
  `userUuid` BINARY(16) NOT NULL,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_USER_MACADDRESS_1_idx` (`userUuid` ASC) VISIBLE,
  CONSTRAINT `fk_USER_MACADDRESS_1`
    FOREIGN KEY (`userUuid`)
    REFERENCES `SkillZBox`.`USER` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkillZBox`.`USER_DEVICE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkillZBox`.`USER_DEVICE` ;

CREATE TABLE IF NOT EXISTS `SkillZBox`.`USER_DEVICE` (
  `device` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `active` TINYINT NOT NULL DEFAULT 0,
  `userUuid` BINARY(16) NOT NULL,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  PRIMARY KEY (`uuid`),
  INDEX `fk_USER_DEVICE_1_idx` (`userUuid` ASC) VISIBLE,
  CONSTRAINT `fk_USER_DEVICE_1`
    FOREIGN KEY (`userUuid`)
    REFERENCES `SkillZBox`.`USER` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkillZBox`.`USER_FRIEND`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkillZBox`.`USER_FRIEND` ;

CREATE TABLE IF NOT EXISTS `SkillZBox`.`USER_FRIEND` (
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user` BINARY(16) NOT NULL,
  `friend` BINARY(16) NOT NULL,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  PRIMARY KEY (`uuid`),
  INDEX `fk_USER_FRIEND_1_idx` (`user` ASC) VISIBLE,
  INDEX `fk_USER_FRIEND_2_idx` (`friend` ASC) VISIBLE,
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  CONSTRAINT `fk_USER_FRIEND_1`
    FOREIGN KEY (`user`)
    REFERENCES `SkillZBox`.`USER` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_FRIEND_2`
    FOREIGN KEY (`friend`)
    REFERENCES `SkillZBox`.`USER` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkillZBox`.`USER_HISTORY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkillZBox`.`USER_HISTORY` ;

CREATE TABLE IF NOT EXISTS `SkillZBox`.`USER_HISTORY` (
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `isMessage` TINYINT NOT NULL DEFAULT 0,
  `isAction` TINYINT NOT NULL DEFAULT 0,
  `userUuid` BINARY(16) NOT NULL,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_USER_HISTORY_1_idx` (`userUuid` ASC) VISIBLE,
  CONSTRAINT `fk_USER_HISTORY_1`
    FOREIGN KEY (`userUuid`)
    REFERENCES `SkillZBox`.`USER` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkillZBox`.`USER_MESSAGE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkillZBox`.`USER_MESSAGE` ;

CREATE TABLE IF NOT EXISTS `SkillZBox`.`USER_MESSAGE` (
  `message` TEXT NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `userHistoryUuid` BINARY(16) NOT NULL,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_USER_MESSAGE_1_idx` (`userHistoryUuid` ASC) VISIBLE,
  CONSTRAINT `fk_USER_MESSAGE_1`
    FOREIGN KEY (`userHistoryUuid`)
    REFERENCES `SkillZBox`.`USER_HISTORY` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkillZBox`.`USER_ACTION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkillZBox`.`USER_ACTION` ;

CREATE TABLE IF NOT EXISTS `SkillZBox`.`USER_ACTION` (
  `log` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `userHistoryUuid` BINARY(16) NOT NULL,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_USER_ACTION_1_idx` (`userHistoryUuid` ASC) VISIBLE,
  CONSTRAINT `fk_USER_ACTION_1`
    FOREIGN KEY (`userHistoryUuid`)
    REFERENCES `SkillZBox`.`USER_HISTORY` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkillZBox`.`ROOM_USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkillZBox`.`ROOM_USER` ;

CREATE TABLE IF NOT EXISTS `SkillZBox`.`ROOM_USER` (
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `isRoomMaster` TINYINT NOT NULL DEFAULT 0,
  `userUuid` BINARY(16) NOT NULL,
  `roomUuid` BINARY(16) NOT NULL,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_ROOM_USER_1_idx` (`roomUuid` ASC) VISIBLE,
  INDEX `fk_ROOM_USER_2_idx` (`userUuid` ASC) VISIBLE,
  CONSTRAINT `fk_ROOM_USER_1`
    FOREIGN KEY (`roomUuid`)
    REFERENCES `SkillZBox`.`ROOM` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ROOM_USER_2`
    FOREIGN KEY (`userUuid`)
    REFERENCES `SkillZBox`.`USER` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkillZBox`.`ROOM_MESSAGE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkillZBox`.`ROOM_MESSAGE` ;

CREATE TABLE IF NOT EXISTS `SkillZBox`.`ROOM_MESSAGE` (
  `message` TEXT NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `hasFiles` TINYINT NOT NULL DEFAULT 0,
  `roomUserUuid` BINARY(16) NOT NULL,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_ROOM_MESSAGE_1_idx` (`roomUserUuid` ASC) VISIBLE,
  CONSTRAINT `fk_ROOM_MESSAGE_1`
    FOREIGN KEY (`roomUserUuid`)
    REFERENCES `SkillZBox`.`ROOM_USER` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkillZBox`.`TAG`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkillZBox`.`TAG` ;

CREATE TABLE IF NOT EXISTS `SkillZBox`.`TAG` (
  `name` VARCHAR(64) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkillZBox`.`ROOM_HAS_TAG`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkillZBox`.`ROOM_HAS_TAG` ;

CREATE TABLE IF NOT EXISTS `SkillZBox`.`ROOM_HAS_TAG` (
  `roomUuid` BINARY(16) NOT NULL,
  `tagUuid` BINARY(16) NOT NULL,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_ROOM_HAS_TAG_1_idx` (`roomUuid` ASC) VISIBLE,
  INDEX `fk_ROOM_HAS_TAG_2_idx` (`tagUuid` ASC) VISIBLE,
  CONSTRAINT `fk_ROOM_HAS_TAG_1`
    FOREIGN KEY (`roomUuid`)
    REFERENCES `SkillZBox`.`ROOM` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ROOM_HAS_TAG_2`
    FOREIGN KEY (`tagUuid`)
    REFERENCES `SkillZBox`.`TAG` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkillZBox`.`CATEGORIE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkillZBox`.`CATEGORIE` ;

CREATE TABLE IF NOT EXISTS `SkillZBox`.`CATEGORIE` (
  `name` VARCHAR(64) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkillZBox`.`ROOM_HAS_CATEGORIE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkillZBox`.`ROOM_HAS_CATEGORIE` ;

CREATE TABLE IF NOT EXISTS `SkillZBox`.`ROOM_HAS_CATEGORIE` (
  `categorieUuid` BINARY(16) NOT NULL,
  `roomUuid` BINARY(16) NOT NULL,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_ROOM_HAS_CATEGORIE_1_idx` (`roomUuid` ASC) VISIBLE,
  INDEX `fk_ROOM_HAS_CATEGORIE_2_idx` (`categorieUuid` ASC) VISIBLE,
  CONSTRAINT `fk_ROOM_HAS_CATEGORIE_1`
    FOREIGN KEY (`roomUuid`)
    REFERENCES `SkillZBox`.`ROOM` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ROOM_HAS_CATEGORIE_2`
    FOREIGN KEY (`categorieUuid`)
    REFERENCES `SkillZBox`.`CATEGORIE` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkillZBox`.`ROOM_MESSAGE_FILE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkillZBox`.`ROOM_MESSAGE_FILE` ;

CREATE TABLE IF NOT EXISTS `SkillZBox`.`ROOM_MESSAGE_FILE` (
  `path` VARCHAR(255) NOT NULL,
  `seed` INT NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `sizeMo` INT NOT NULL,
  `roomMessageUuid` BINARY(16) NOT NULL,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_ROOM_MESSAGE_FILE_1_idx` (`roomMessageUuid` ASC) VISIBLE,
  CONSTRAINT `fk_ROOM_MESSAGE_FILE_1`
    FOREIGN KEY (`roomMessageUuid`)
    REFERENCES `SkillZBox`.`ROOM_MESSAGE` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = ascii;


-- -----------------------------------------------------
-- Table `SkillZBox`.`USER_REPORT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkillZBox`.`USER_REPORT` ;

CREATE TABLE IF NOT EXISTS `SkillZBox`.`USER_REPORT` (
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `reason` TEXT NOT NULL,
  `userSendReport` BINARY(16) NOT NULL,
  `userReported` BINARY(16) NOT NULL,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_USER_REPORT_1_idx` (`userSendReport` ASC) VISIBLE,
  INDEX `fk_USER_REPORT_2_idx` (`userReported` ASC) VISIBLE,
  CONSTRAINT `fk_USER_REPORT_1`
    FOREIGN KEY (`userSendReport`)
    REFERENCES `SkillZBox`.`USER` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_REPORT_2`
    FOREIGN KEY (`userReported`)
    REFERENCES `SkillZBox`.`USER` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkillZBox`.`ROOM_ACTION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkillZBox`.`ROOM_ACTION` ;

CREATE TABLE IF NOT EXISTS `SkillZBox`.`ROOM_ACTION` (
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `action` TEXT NOT NULL,
  `roomUserUuid` BINARY(16) NOT NULL,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_ROOM_ACTION_1_idx` (`roomUserUuid` ASC) VISIBLE,
  CONSTRAINT `fk_ROOM_ACTION_1`
    FOREIGN KEY (`roomUserUuid`)
    REFERENCES `SkillZBox`.`ROOM_USER` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkillZBox`.`USER_TOKEN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkillZBox`.`USER_TOKEN` ;

CREATE TABLE IF NOT EXISTS `SkillZBox`.`USER_TOKEN` (
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `expireAt` DATETIME NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `userUuid` BINARY(16) NOT NULL,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  UNIQUE INDEX `token_UNIQUE` (`token` ASC) VISIBLE,
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_USER_TOKEN_1_idx` (`userUuid` ASC) VISIBLE,
  UNIQUE INDEX `userUuid_UNIQUE` (`userUuid` ASC) VISIBLE,
  CONSTRAINT `fk_USER_TOKEN_1`
    FOREIGN KEY (`userUuid`)
    REFERENCES `SkillZBox`.`USER` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkillZBox`.`USER_FRIEND_REQUESTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkillZBox`.`USER_FRIEND_REQUESTS` ;

CREATE TABLE IF NOT EXISTS `SkillZBox`.`USER_FRIEND_REQUESTS` (
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `userSendingRequest` BINARY(16) NOT NULL,
  `userRequested` BINARY(16) NOT NULL,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  PRIMARY KEY (`uuid`),
  INDEX `fk_USER_FRIEND_1_idx` (`userSendingRequest` ASC) VISIBLE,
  INDEX `fk_USER_FRIEND_2_idx` (`userRequested` ASC) VISIBLE,
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  CONSTRAINT `fk_USER_FRIEND_10`
    FOREIGN KEY (`userSendingRequest`)
    REFERENCES `SkillZBox`.`USER` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_FRIEND_20`
    FOREIGN KEY (`userRequested`)
    REFERENCES `SkillZBox`.`USER` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
