-- MySQL Script generated by MySQL Workbench
-- mar. 12 avril 2022 11:58:39
-- Model: SkillzBox    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SkillzBox
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SkillzBox` ;

-- -----------------------------------------------------
-- Schema SkillzBox
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SkillzBox` ;
USE `SkillzBox` ;

-- -----------------------------------------------------
-- Table `SkillzBox`.`USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkillzBox`.`USER` ;

CREATE TABLE IF NOT EXISTS `SkillzBox`.`USER` (
  `email` VARCHAR(255) NOT NULL,
  `username` VARCHAR(16) COLLATE 'Default Collation' NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `token` VARCHAR(38) NOT NULL,
  `isVerified` TINYINT NOT NULL DEFAULT 0,
  `role` VARCHAR(45) NOT NULL COMMENT 'enum(\'admin\', \'moderator\', \'user\')',
  `isConnected` TINYINT NOT NULL DEFAULT 0,
  `isBlackListed` TINYINT NOT NULL DEFAULT 0,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `uuid` VARCHAR(38) NOT NULL,
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkillzBox`.`ROOM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkillzBox`.`ROOM` ;

CREATE TABLE IF NOT EXISTS `SkillzBox`.`ROOM` (
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `optionLimitUser` INT NOT NULL,
  `uuid` VARCHAR(38) NOT NULL,
  PRIMARY KEY (`uuid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkillzBox`.`USER_LOGO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkillzBox`.`USER_LOGO` ;

CREATE TABLE IF NOT EXISTS `SkillzBox`.`USER_LOGO` (
  `path` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `seed` INT NOT NULL,
  `sizeMo` INT NOT NULL,
  `active` TINYINT NOT NULL,
  `userUuid` VARCHAR(38) NOT NULL,
  `uuid` VARCHAR(38) NOT NULL,
  PRIMARY KEY (`uuid`),
  INDEX `user_uuid_idx` (`userUuid` ASC) VISIBLE,
  CONSTRAINT
    FOREIGN KEY (`userUuid`)
    REFERENCES `SkillzBox`.`USER` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkillzBox`.`USER_IP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkillzBox`.`USER_IP` ;

CREATE TABLE IF NOT EXISTS `SkillzBox`.`USER_IP` (
  `ip` VARCHAR(16) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `active` TINYINT NOT NULL,
  `userUuid` VARCHAR(38) NOT NULL,
  `uuid` VARCHAR(38) NOT NULL,
  PRIMARY KEY (`uuid`),
  INDEX `user_uuid_idx` (`userUuid` ASC) VISIBLE,
  CONSTRAINT
    FOREIGN KEY (`userUuid`)
    REFERENCES `SkillzBox`.`USER` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkillzBox`.`USER_MACADDRESS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkillzBox`.`USER_MACADDRESS` ;

CREATE TABLE IF NOT EXISTS `SkillzBox`.`USER_MACADDRESS` (
  `macAdress` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `active` TINYINT NOT NULL,
  `userUuid` VARCHAR(38) NOT NULL,
  `uuid` VARCHAR(38) NOT NULL,
  PRIMARY KEY (`uuid`),
  INDEX `user_uuid_idx` (`userUuid` ASC) VISIBLE,
  CONSTRAINT
    FOREIGN KEY (`userUuid`)
    REFERENCES `SkillzBox`.`USER` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkillzBox`.`USER_DEVICE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkillzBox`.`USER_DEVICE` ;

CREATE TABLE IF NOT EXISTS `SkillzBox`.`USER_DEVICE` (
  `device` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `active` TINYINT NOT NULL,
  `userUuid` VARCHAR(38) NOT NULL,
  `uuid` VARCHAR(38) NOT NULL,
  PRIMARY KEY (`uuid`),
  INDEX `user_uuid_idx` (`userUuid` ASC) VISIBLE,
  CONSTRAINT
    FOREIGN KEY (`userUuid`)
    REFERENCES `SkillzBox`.`USER` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkillzBox`.`USER_FRIEND`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkillzBox`.`USER_FRIEND` ;

CREATE TABLE IF NOT EXISTS `SkillzBox`.`USER_FRIEND` (
  `isConnected` TINYINT NOT NULL DEFAULT 0,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `userUuid` VARCHAR(38) NOT NULL,
  `friendUuid` VARCHAR(38) NOT NULL,
  `uuid` VARCHAR(38) NOT NULL,
  PRIMARY KEY (`uuid`),
  INDEX `user_uuid_idx` (`userUuid` ASC) VISIBLE,
  INDEX `friend_uuid_idx` (`friendUuid` ASC) VISIBLE,
  CONSTRAINT
    FOREIGN KEY (`userUuid`)
    REFERENCES `SkillzBox`.`USER` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT
    FOREIGN KEY (`friendUuid`)
    REFERENCES `SkillzBox`.`USER` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkillzBox`.`USER_HISTORY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkillzBox`.`USER_HISTORY` ;

CREATE TABLE IF NOT EXISTS `SkillzBox`.`USER_HISTORY` (
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `isMessage` TINYINT NOT NULL DEFAULT 0,
  `isAction` TINYINT NOT NULL DEFAULT 0,
  `userUuid` VARCHAR(38) NOT NULL,
  `uuid` VARCHAR(38) NOT NULL DEFAULT '',
  PRIMARY KEY (`uuid`),
  INDEX `user_uuid_idx` (`userUuid` ASC) VISIBLE,
  CONSTRAINT
    FOREIGN KEY (`userUuid`)
    REFERENCES `SkillzBox`.`USER` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkillzBox`.`USER_MESSAGE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkillzBox`.`USER_MESSAGE` ;

CREATE TABLE IF NOT EXISTS `SkillzBox`.`USER_MESSAGE` (
  `message` TEXT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `userHistoryUuid` VARCHAR(38) NOT NULL,
  `uuid` VARCHAR(38) NOT NULL,
  PRIMARY KEY (`uuid`),
  INDEX `user_history_uuid_idx` (`userHistoryUuid` ASC) VISIBLE,
  CONSTRAINT
    FOREIGN KEY (`userHistoryUuid`)
    REFERENCES `SkillzBox`.`USER_HISTORY` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkillzBox`.`USER_ACTION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkillzBox`.`USER_ACTION` ;

CREATE TABLE IF NOT EXISTS `SkillzBox`.`USER_ACTION` (
  `log` VARCHAR(255) NOT NULL,
  `userHistoryUuid` VARCHAR(38) NOT NULL,
  `uuid` VARCHAR(38) NOT NULL,
  PRIMARY KEY (`uuid`),
  INDEX `user_history_uuid_idx` (`userHistoryUuid` ASC) VISIBLE,
  CONSTRAINT
    FOREIGN KEY (`userHistoryUuid`)
    REFERENCES `SkillzBox`.`USER_HISTORY` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkillzBox`.`ROOM_USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkillzBox`.`ROOM_USER` ;

CREATE TABLE IF NOT EXISTS `SkillzBox`.`ROOM_USER` (
  `createdAt` DATETIME NOT NULL,
  `roomUuid` VARCHAR(38) NOT NULL,
  `isRoomMaster` TINYINT NOT NULL,
  `userUuid` VARCHAR(38) NOT NULL,
  `uuid` VARCHAR(38) NOT NULL,
  PRIMARY KEY (`uuid`),
  INDEX `user_uuid_idx` (`userUuid` ASC) VISIBLE,
  INDEX `room_uuid_idx` (`roomUuid` ASC) VISIBLE,
  CONSTRAINT
    FOREIGN KEY (`userUuid`)
    REFERENCES `SkillzBox`.`USER` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT
    FOREIGN KEY (`roomUuid`)
    REFERENCES `SkillzBox`.`ROOM` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkillzBox`.`ROOM_MESSAGE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkillzBox`.`ROOM_MESSAGE` ;

CREATE TABLE IF NOT EXISTS `SkillzBox`.`ROOM_MESSAGE` (
  `message` TEXT NOT NULL,
  `createdAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `hasFiles` TINYINT NOT NULL DEFAULT 0,
  `roomUserUuid` VARCHAR(38) NOT NULL,
  `uuid` VARCHAR(38) NOT NULL,
  PRIMARY KEY (`uuid`),
  INDEX `room_user_uuid_idx` (`roomUserUuid` ASC) VISIBLE,
  CONSTRAINT
    FOREIGN KEY (`roomUserUuid`)
    REFERENCES `SkillzBox`.`ROOM_USER` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkillzBox`.`TAG`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkillzBox`.`TAG` ;

CREATE TABLE IF NOT EXISTS `SkillzBox`.`TAG` (
  `name` VARCHAR(16) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `uuid` VARCHAR(38) NOT NULL,
  PRIMARY KEY (`uuid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkillzBox`.`ROOM_HAS_TAG`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkillzBox`.`ROOM_HAS_TAG` ;

CREATE TABLE IF NOT EXISTS `SkillzBox`.`ROOM_HAS_TAG` (
  `roomUuid` VARCHAR(38) NOT NULL,
  `tagUuid` VARCHAR(38) NOT NULL,
  `uuid` VARCHAR(38) NOT NULL,
  PRIMARY KEY (`uuid`),
  INDEX `room_uuid_idx` (`roomUuid` ASC) VISIBLE,
  INDEX `tag_uuid_idx` (`tagUuid` ASC) VISIBLE,
  CONSTRAINT
    FOREIGN KEY (`roomUuid`)
    REFERENCES `SkillzBox`.`ROOM` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT ` `
    FOREIGN KEY (`tagUuid`)
    REFERENCES `SkillzBox`.`TAG` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkillzBox`.`CATEGORIE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkillzBox`.`CATEGORIE` ;

CREATE TABLE IF NOT EXISTS `SkillzBox`.`CATEGORIE` (
  `name` VARCHAR(16) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `uuid` VARCHAR(38) NOT NULL,
  PRIMARY KEY (`uuid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkillzBox`.`ROOM_HAS_CATEGORIE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkillzBox`.`ROOM_HAS_CATEGORIE` ;

CREATE TABLE IF NOT EXISTS `SkillzBox`.`ROOM_HAS_CATEGORIE` (
  `categorieUuid` VARCHAR(38) NOT NULL,
  `roomUuid` VARCHAR(38) NOT NULL,
  `uuid` VARCHAR(38) NOT NULL,
  PRIMARY KEY (`uuid`),
  INDEX `room_uuid_idx` (`roomUuid` ASC) VISIBLE,
  INDEX `categorie_uuid_idx` (`categorieUuid` ASC) VISIBLE,
  CONSTRAINT
    FOREIGN KEY (`roomUuid`)
    REFERENCES `SkillzBox`.`ROOM` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT
    FOREIGN KEY (`categorieUuid`)
    REFERENCES `SkillzBox`.`CATEGORIE` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkillzBox`.`ROOM_MESSAGE_FILE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkillzBox`.`ROOM_MESSAGE_FILE` ;

CREATE TABLE IF NOT EXISTS `SkillzBox`.`ROOM_MESSAGE_FILE` (
  `path` VARCHAR(255) NOT NULL,
  `seed` INT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `sizeMo` INT NOT NULL,
  `roomMessageUuid` VARCHAR(38) NOT NULL,
  `uuid` VARCHAR(38) NOT NULL,
  PRIMARY KEY (`uuid`),
  INDEX `room_tchat_uuid_idx` (`roomMessageUuid` ASC) VISIBLE,
  CONSTRAINT
    FOREIGN KEY (`roomMessageUuid`)
    REFERENCES `SkillzBox`.`ROOM_MESSAGE` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = ascii;


-- -----------------------------------------------------
-- Table `SkillzBox`.`USER_REPORT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkillzBox`.`USER_REPORT` ;

CREATE TABLE IF NOT EXISTS `SkillzBox`.`USER_REPORT` (
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `reason` TEXT NOT NULL,
  `userSendReport` VARCHAR(36) NOT NULL,
  `userReported` VARCHAR(36) NOT NULL,
  `uuid` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`uuid`),
  INDEX `user_send_report_idx` (`userSendReport` ASC) VISIBLE,
  INDEX `user_reported_idx` (`userReported` ASC) VISIBLE,
  CONSTRAINT
    FOREIGN KEY (`userSendReport`)
    REFERENCES `SkillzBox`.`USER` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT
    FOREIGN KEY (`userReported`)
    REFERENCES `SkillzBox`.`USER` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkillzBox`.`ROOM_ACTION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkillzBox`.`ROOM_ACTION` ;

CREATE TABLE IF NOT EXISTS `SkillzBox`.`ROOM_ACTION` (
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `action` TEXT NOT NULL,
  `roomUserUuid` VARCHAR(36) NOT NULL,
  `uuid` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`uuid`),
  INDEX `room_user_uuid_idx` (`roomUserUuid` ASC) VISIBLE,
  CONSTRAINT
    FOREIGN KEY (`roomUserUuid`)
    REFERENCES `SkillzBox`.`ROOM_USER` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
