export enum CodeError {
    ACCOUNT_UTILS_CHECK_POST_CONTAIN_MAIL_OR_USERNAME_AND_PASSWORD = 'AccountUtils::checkPostContainMailORUsernameANDPassword',
    ACCOUNT_UTILS_CHECK_POST_CONTAIN_MAIL_AND_USERNAME_AND_PASSWORD = 'AccountUtils:checkPostContainMailANDUserANDPassword',
    ACCOUNT_UTILS_CHECK_POST_CONTAIN_IP_AND_MACADDRESS_AND_DEVICE_TYPE = 'AccountUtils::checkPostContainIpANDMacAddressANDDeviceType',
    ACCOUNT_UTILS_CHECK_SYNTAXE_USERNAME = 'AccountUtils::checkSyntaxeUsername',
    ACCOUNT_UTILS_GET_USER_BY_SEARCH = 'AccountUtils::getUserBySearch',
    ACCOUNT_UTILS_GET_TOKEN_BY_USER = 'AccountUtils::getTokenByUser',
    ACCOUNT_UTILS_CREATE_TOKEN = 'AccountUtils::createToken',
    ACCOUNT_UTILS_SEND_EMAIL_VERIFICATION = 'AccountUtils::sendMailVerification',
    ACCOUNT_UTILS_VERIFY_TOKEN_SIGNATURE = 'AccountUtils::verifyTokenSignature',
    ACCOUNT_UTILS_VERIFY_TOKEN_EXPIRATION = 'AccountUtils::verifyTokenExpiration',
    ACCOUNT_UTILS_VERIFY_USER = 'AccountUtils::verifyUser',
    ACCOUNT_UTILS_VERIFY_LOGIN = 'AccountUtilsError:verifyLogin',
    ACCOUNT_UTILS_VERIFY_BLACKLIST = 'AccountUtilsError:verifyIfBlacklisted',
    ACCOUNT_UTILS_UPDATE_USER_IS_CONNECTED = 'AccountUtilsError:updateUserIsConnected',
    ACCOUNT_UTILS_ADD_NEW_IP_OR_UPDATE = 'AccountUtilsError:addNewIpOrUpdate',
    ACCOUNT_UTILS_ADD_NEW_MACADDRESS_OR_UPDATE = 'AccountUtilsError:addNewMacAddressOrUpdate',
    ACCOUNT_UTILS_ADD_NEW_DEVICE_OR_UPDATE = 'AccountUtilsError:addNewDeviceOrUpdate',
}
